<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewStandardRptPageGraphical.aspx.cs" Inherits="TAMSR2.Reports.ViewStandardRptPageGraphical" %>

<%@ Register Assembly="CrystalDecisions.Web, Version=13.0.2000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304" Namespace="CrystalDecisions.Web" TagPrefix="CR" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
        .highcharts-contextmenu div:first-child hr{
            display:none;
        }
        .highcharts-contextmenu div:first-child div {
            display:none;
        }
        .highcharts-contextmenu div:first-child div:first-child {
            display:block;
        }

    </style>
</head>
<body>
    <form id="form1" runat="server">
        <header>
        </header>
        <section>
            <div id="container" style="min-height:400px">
            </div>
        </section>
        <footer>
        </footer>
    </form>

    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <script src="../assets/<%= "En" %>/plugins/jquery-1.8.3.min.js" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="../assets/<%= "En" %>/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
    <script src="../assets/<%= "En" %>/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!--[if lt IE 9]>
   <script src="../assets/<%= "En" %>/plugins/excanvas.js"></script>
   <script src="../assets/<%= "En" %>/plugins/respond.js"></script>  
   <![endif]-->
    <script src="../assets/<%= "En" %>/plugins/breakpoints/breakpoints.js" type="text/javascript"></script>
    <!-- IMPORTANT! jquery.slimscroll.min.js depends on jquery-ui-1.10.1.custom.min.js -->
    <script src="../assets/<%= "En" %>/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="../assets/<%= "En" %>/plugins/jquery.blockui.js" type="text/javascript"></script>
    <script src="../assets/<%= "En" %>/plugins/jquery.cookie.js" type="text/javascript"></script>
    <script src="../assets/<%= "En" %>/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="../assets/<%= "En" %>/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="../assets/<%= "En" %>/plugins/jquery-validation/dist/additional-methods.min.js"></script>
    <script type="text/javascript" src="../assets/<%= "En" %>/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
    <script type="text/javascript" src="../assets/<%= "En" %>/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="../assets/<%= "En" %>/plugins/data-tables/jquery.dataTables.js"></script>
    <script type="text/javascript" src="../assets/<%= "En" %>/plugins/data-tables/DT_bootstrap.js"></script>


    <!--Script references. -->
    <!--Reference the SignalR library. -->
    <%--<script src="../Scripts/jquery.signalR-1.1.0.min.js"></script>--%>
    <%--<!--Reference the autogenerated SignalR hub script. -->
    <script src="../signalr/hubs"></script>

    --%><!-- END PAGE LEVEL PLUGINS -->

    <script type="text/javascript" src="../assets/<%=  "en" %>/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>
    <script type="text/javascript" src="../assets/<%=  "en" %>/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src='../Assets/<%= "en" %>/plugins/jquery-validation/dist/jquery.validate.min.js' type='text/javascript'></script>
    <script src="../assets/<%=  "en" %>/scripts/app.js"></script>
    <script src="../assets/<%=  "en" %>/scripts/table-managed.js"></script>
    <script src="../Scripts/jquery.loadmask.js"></script>

    <script src="../Styles/HighCharts/highcharts.js" type="text/javascript"></script>
    <script src="../Styles/HighCharts/drilldown.js" type="text/javascript"></script>
    <script src="../Styles/HighCharts/exporting.js"></script>
    <!-- START OF PAGE LEVEL SCRIPT-->
    <!-- START OF PAGE LEVEL SCRIPT-->
    <script>
        var ReportMetaData;
        var ReportsData;
        $(document).ready(function () {
            SetContainerResolution();
            ReportMetaData = <%= ReportMetaData %>
            ReportsData = <%= ReportJSON %>
            GenerateChart(ReportsData,ReportMetaData);
        });
        function SetContainerResolution(){
            var height =  screen.height;
            var width =  screen.height;
            height =  height -150;
            $("#container").height(height);
            return height;
            
        }
        function GenerateChart(ReportsData,ReportMetaData){
            var chartCategories = [];

            for (var i = 0; i < ReportsData.length; i++) {
                chartCategories.push(ReportsData[i].OrganizationName);
            }
            var  seriesName = [{Text: 'No Of Absent' ,Key : 'NoOfAbsentDays',Color:'#cc3f44'},
                               {Text: 'No Of Holiday' ,Key : 'NoofHoliday',Color:'#a1c436'},
                               {Text: 'No of Early Out' ,Key : 'NoOfEarlyOut',Color:'#7c38bc'},
                               {Text: 'No Of Late In' ,Key : 'NoOfLate',Color:'#5fb4ef'},
                               {Text: 'No Of Leaves' ,Key : 'TotalDaysOfLeave',Color:'#ff851b'}];

            var series = [];
          
            for (var i = 0; i < seriesName.length; i++) {
                series.push({name:seriesName[i].Text,data:[],Key:seriesName[i].Key,color:seriesName[i].Color});
            };

            for (var i = 0; i < series.length; i++)
            {
                for (var j = 0; j < ReportsData.length; j++) {
                    series[i].data.push( ReportsData[j][series[i].Key]);
                }
            }
            console.log(chartCategories);
            console.log(series);
            var subtitle =   "From Date : " + window.ReportMetaData.FromDate  +"     To Date : " + window.ReportMetaData.ToDate;
            if(ReportMetaData.EmployeeName){
                subtitle+= "<br /><br />Employee Name : " + ReportMetaData.EmployeeName;
            }
            $('#container').highcharts({
                chart: {
                    type: 'column',
                    inverted: false
                },
                title: { 
                    text:  '<div><img width="200" height="200" src="../Images/app-logo.png" /></div><div>'+ReportMetaData.ReportName+'</div>',
                    useHTML: true,
                    style: {
                        color: '#000000',
                        fontWeight: 'bold'
                    }
                },
                subtitle: { 
                    text: subtitle,
                    useHTML: true,
                    style: {
                        color: '#000000',
                        fontWeight: 'bold'
                    }
                },
                xAxis: {
                    categories: chartCategories,
                    crosshair: true
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Value'
                    },
                    max:140
                    
                },
                tooltip: {
                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                        '<td style="padding:0"><b>{point.y} </b></td></tr>',
                    footerFormat: '</table>',
                    shared: true,
                    useHTML: true
                },
                plotOptions: {
                    series: {
                        pointWidth: 20
                    },
                    column: {
                        pointPadding: 0.1,
                        borderWidth: 1
                    }
                },
                series:series,
                credits: {
                    enabled: false
                },
                exporting: {

                    filename:ReportMetaData.ReportName,

                    buttons: {
                        buttons: {
                            printButton: {
                                symbol: 'circle'
                            },
                            exportButton: {
                                enabled: false
                            }    
                        }
                    }
                }
               
            });
        
        
        };
    </script>

</body>


</html>
